project2/madlibs/urls.py
from django.urls import path
from . import views

app_name = 'madlibs'
urlpatterns = [
    # /madlibs
    path('', views.index, name="index"),
    # /madlibs/1 /madlibs/2
    path('madlib/', views.madlibForm, name='madlib-form')
]

project2/project2/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('madlibs.urls')),
]

project2/madlibs/models.py
from django.db import models

# Create your models here.
class MadLib(models.Model):
    title = models.CharField(max_length=100)
    template = models.TextField()

    def __str__(self):
        return self.title

project2/madlibs/forms.py
from django import forms
from .models import MadLib

class MadLibForm(forms.Form):
    noun = forms.CharField(label='Noun', max_length=100)
    verb = forms.CharField(label='Verb (ending in "ing")', max_length=100)
    adjective = forms.CharField(label='Adjective', max_length=100)
    place = forms.CharField(label='Place', max_length=100)
    name = forms.CharField(label="Person's Name", max_length=100)
    color = forms.CharField(label='Color', max_length=100)
    noun2 = forms.CharField(label='Plural Noun', max_length=100)

project2/madlibs/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import MadLib
from .forms import MadLibForm
import random
# add this in if necessary
# from django.contrib.auth.decorators import login_required
# from django.contrib import messages


# Create your views here.

def index(request):
    return render(request, 'madlibs/index.html', {"intro": "Welcome to my madlib project!"})

def madlibForm(request):
    if request.method == 'POST':
        form = MadLibForm(request.POST)
        if form.is_valid():
            story = random.choice(MadLib.objects.all())
            # **form.cleaned_data:
            # the ** syntax passes the form information (key-value pair) into placeholders within the madlib
            madlib = story.template.format(**form.cleaned_data)
            return render(request, 'madlibs/story.html', {'madlib': madlib, 'title': story.title})
    else:
        form = MadLibForm()
    return render(request, 'madlibs/madlib-form.html', {'form': form})

# User: CodySquadroni
# Password: YouRock!

project2/madlibs/templates/madlibs/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Document</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" 
        integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" 
        integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>
</head>
<body class="bg-dark text-white-50">
    <nav class="navbar bg-secondary">
            <a href="{% url 'madlibs:index' %}" class="navbar-brand text-light">Home</a>
            <div class="navbar">
                <a href="{% url 'madlibs:madlib-form' %}" class="nav-item nav-link text-light">Random</a>
                {% comment %} <a href="{% url '' %}" class="nav-item nav-link text-light">Genre</a> {% endcomment %}
    </nav>
    {% block body %}
    {% endblock %}
</body>
</html>

project2/madlibs/templates/madlibs/index.html
{% extends 'madlibs/base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% block body %}
        <h1 class="text-center">{{ intro }}</h1>
        <div class="row d-flex justify-content-center">
            {% comment %} mad lib generic image display? {% endcomment %}
            <div class="col-md-3 m-2">
                <h2><a href={% url 'madlibs:madlib-form' %}>Create a mad lib story!</a></h2>
            </div>
        </div>
    {% endblock %}
            
</body>
</html>

project2/madlibs/templates/madlibs/madlib-form.html
{% extends 'madlibs/base.html' %}

{% block body %}
<form method="POST">
    {% csrf_token %}
    {{ form }}
    <button type="submit">MadLib!</button>
</form>
{% endblock %}

project2/madlibs/templates/madlibs/story.html
{% extends 'madlibs/base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% block body %}
        <h1 class="m-1 text-center">{{ title }}</h1>
        <div class="d-flex justify-content-center">
            <div class="col-md-6 text-center">
                <p class="mt-3">{{ madlib }}</p>
            </div>
        </div>
    {% endblock %}
</body>
</html>